# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abeef0c966bbd9ea26e2200ff91413e70f3e8272c36d940d0e7706efed67ef3c68c781027202f9bdba8afcca1315fbe258bfec2e69f71a46dae774862cd17300

test:
  secret_key_base: 1bbb20f9bbaf253659423936b16c4918d7eb40d089530ce93bea01eebaca0770d1b85de5425b3396f50d0ac7f54ae4161eda3b62844156ef0e7a9f1ce66bcc7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
